language: ruby
rvm:
 - 2.1.0
 - 2.0.0
 - 1.9.3
gemfile:
 - Gemfile
branches:
  only:
    - devel
    - travis
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libicu-dev
env:
  global:
    - TRAVIS_BUILD_DIR="redmine_git_hosting"
