baseurl: /redmine_git_hosting

data:
  project:
    name: Redmine Git Hosting
    description: A Redmine plugin which makes configuring your own Git hosting easy ;)
    repository: https://github.com/jbox-web/redmine_git_hosting

    github_user: jbox-web
    github_repository: redmine_git_hosting

    release:
      year: 2014
      version: v0.7.6

    author:
      name: JBox Web
      url: http://www.jbox-web.com/

    licence:
      name: MIT
      url: http://opensource.org/licenses/MIT

  lang: en

  google_tracker: UA-36504891-3

  favicons:
    - /assets/2014/04/21/favicon-152.png

  theme:
    stylesheets:
      - //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
      - //maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css

    javascripts:
      - //code.jquery.com/jquery-1.11.1.min.js
      - //code.jquery.com/ui/1.10.4/jquery-ui.min.js
      - //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
      - //cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.1.5/ZeroClipboard.min.js
      - //platform.twitter.com/widgets.js

markdown: kramdown

kramdown:
  input: GFM

gems:
- jekyll-sitemap

excerpt_separator: "##########"
