baseurl: /redmine_git_hosting
host: 127.0.0.1
port: 4000

destination: _site/redmine_git_hosting

# the theme will include the page with id: homepage in the frontmatter on the index.html page.
homepage_id: homepage

# the theme will include the page with id: footer in the frontmatter.
footer_id: footer


## build settings -- leave as is

markdown: kramdown

kramdown:
  input: GFM

gems:
- jekyll-sitemap

excerpt_separator: "##########"

highlighter: pygments

exclude: # put all files or directories that you want to exclude from your project here.
  - "Gemfile"
  - "Gemfile.lock"
  - _drafts
  - _site/documentation-theme-jekyll
  - bower_components

# these are defaults that get applied to each page or post. you don't have to set these settings in the frontmatter if you put them here. But frontmatter settings will override the configs here.
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      search: include
  -
    scope:
      path: ""
      type: "posts"
    values:
      search: include

# sass:
#   sass_dir: _sass

# placed here for translation purposes
search_placeholder_text: search...
search_no_results_text: No results found.

collections:
  tooltips:
    output: true
