---
:environment: development
:daemon: false
:concurrency: 1
# :pidfile: tmp/pids/worker_redmine_git_hosting.pid
# :logfile: log/worker_redmine_git_hosting.log
:require: ./
:verbose: true
:queues:
  - [git_hosting, 1]
